#!/bin/bash

SHELL_PATH=$DOTFILES/shell
export ALIASES_PATH=$SHELL_PATH/aliases

. $SHELL_PATH/lib/utils
. $SHELL_PATH/lib/api
. $SHELL_PATH/lib/file
. $SHELL_PATH/lib/print
. $SHELL_PATH/lib/symlink

distro=$(get-distro)

case $distro in
ubuntu | Darwin | arch | MINGW*)
  . $ALIASES_PATH/_linux
  ;;
esac

case $distro in
ubuntu)
  . $ALIASES_PATH/_ubuntu
  ;;
Darwin)
  . $ALIASES_PATH/_osx
  ;;
arch)
  . ${ALIASES_PATH}/_arch
  ;;
esac
