#!/bin/bash

SHELL_PATH=$DOTFILES/shell
export ALIASES_PATH=$SHELL_PATH/aliases
export DEVOPS_PATH=$SHELL_PATH/devops

. $SHELL_PATH/lib/utils
. $SHELL_PATH/lib/api
. $SHELL_PATH/lib/file
. $SHELL_PATH/lib/print
. $SHELL_PATH/lib/symlink

distro=$(get-distro)

case $distro in
ubuntu | Darwin | arch | MINGW*)
  . $ALIASES_PATH/os/linux
  ;;
esac

case $distro in
ubuntu)
  . $ALIASES_PATH/os/ubuntu
  ;;
Darwin)
  . $ALIASES_PATH/os/osx
  ;;
MINGW*)
  . $ALIASES_PATH/os/gitbash
  ;;
arch)
  . ${ALIASES_PATH}/os/arch
  ;;
esac
