---
casks:
  ack:
  android-sdk:
  ansible:
  awscli:
  cmake:
  diff-so-fancy:
  docker-compose:
  exa:
  feh:
  ffmpeg:
  figlet:
  fzf:
  gd:
  gnupg:
  googler:
  graphviz:
  htop:
  httpd:
  httpie:
  imagemagick:
  isync:
  jpeg:
  jq:
  kubernetes-cli:
  libyaml:
  lynx:
  mas:
  msmtp:
  mutt:
  neomutt:
  pass:
  pinentry-mac:
  postman:
  powerline-go:
  python:
  racket:
  ranger:
  rename:
  Schniz/tap/fnm:
  starship:
  subversion:
  termius:
  tig:
  tmux:
  tree:
  watch:
  wget:
  xpdf:
  xz:
  zopfli:
