---
casks:
  android-sdk:
  android-studio:
  barrier:
  chromium:
  font-hack-nerd-font:
  google-chrome:
  google-hangouts:
  hammerspoon:
  adoptopenjdk/openjdk/adoptopenjdk8:
  anydesk:
  docker:
  dropbox:
  figma:
  gpg-suite:
  mactex-no-gui:
  openvpn-connect:
  pluralsight:
  soapui:
  termius:
  the-unarchiver:
  use-engine:
  xquartz:
  intellij-idea:
  iterm2:
  microsoft-edge-dev:
  microsoft-office:
  microsoft-teams:
  notion:
  now:
  skype:
  slack:
  spotify:
  telegram:
  visual-studio-code:
  vlc:
  webstorm:
