# SSH key check
test -f ~/.ssh/id_rsa
[ "$?" = 0 ] && SSHRSA_OK=yes
[ -z $SSHRSA_OK ] && >&2 echo "[WARNING] No id_rsa SSH private key found, SSH functionalities might not work"

# Timezone check
[ -z $TZ ] && >&2 echo "[WARNING] TZ environment variable not set, time might be wrong!"


# SSH AGENT
# keychain --nogui $HOME/.ssh/id_rsa
# source $HOME/.keychain/rsurj-desk-sh

# FNM
eval "$(fnm env)"

# STARSHIP PROMPT
eval "$(starship init zsh)"
