#!/bin/bash

. $ALIASES_PATH/utils.linux
. $ALIASES_PATH/git.linux
. $ALIASES_PATH/docker.linux
. $ALIASES_PATH/npm.global
. $ALIASES_PATH/display.linux
. $ALIASES_PATH/pip.linux

. $DEVOPS_PATH/bitbucket
. $DEVOPS_PATH/gitlab
. $DEVOPS_PATH/postgres
. $DEVOPS_PATH/sonar

alias ..="cd .."
alias ...="cd ..\/.."
alias ....="cd ..\/..\/.."
alias .....="cd ..\/..\/..\/.."

alias pubkey="xclip -sel clip ~/.ssh/id_rsa.pub | printf '=> Public key copied to pasteboard.\n'"
alias genpass="gpg --gen-random --armor 1 13"

function symlink-dotfiles() {
  symlink-files $DOTFILES/files $HOME
}

function uuid() {
  cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
}

function tmp_file() {
  local id=$(uuid)
  local extension=${1:-"json"}
  echo "" >/tmp/$id.$extension
  echo /tmp/$id.$extension
}

# WIP
function yaml_from_list() { # 1:ARRAY_LIST
  local YAML_FILE=$(tmp_file yaml)
  yq -iy --null-input '.data' $YAML_FILE

  for item in $@; do
    echo "$item?: "
    read answer
    yq -iy ".data.$item = \"$answer\"" $YAML_FILE
  done

  echo $YAML_FILE
}

if [ -x "$(command -v codium)" ]; then
  code() { codium $@; }
fi
