#!/bin/bash

alias fd="open ."

alias diskspace_report="df -P -kHl"
alias free_space="df -h"

alias chromedebug="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"

alias reload="exec ${SHELL} -l"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias flush_dns="sudo killall -HUP mDNSResponder"

alias upda='brew update; brew outdated; brew upgrade; brew cleanup; mas upgrade'

alias gpgreset="gpgconf --kill all"

uuid() {
  printf "%04x%04x-%04x-%04x-%04x-%04x%04x%04x\n" \
    $RANDOM $RANDOM \
    $RANDOM \
    $(($RANDOM & 0x0fff | 0x4000)) \
    $(($RANDOM & 0x3fff | 0x8000)) \
    $RANDOM $RANDOM $RANDOM
}
