--- # ---
- name: brew httpd
  shell: brew install httpd
- name: brew ack
  shell: brew install ack
- name: brew cmake
  shell: brew install cmake
- name: brew diff-so-fancy
  shell: brew install diff-so-fancy
- name: brew exa
  shell: brew install exa
- name: brew ffmpeg
  shell: brew install ffmpeg
- name: brew figlet
  shell: brew install figlet
- name: brew fzf
  shell: brew install fzf
- name: brew gd
  shell: brew install gd
- name: brew gnupg
  shell: brew install gnupg
- name: brew googler
  shell: brew install googler
- name: brew graphviz
  shell: brew install graphviz
- name: brew htop
  shell: brew install htop
- name: brew imagemagick
  shell: brew install imagemagick
- name: brew jpeg
  shell: brew install jpeg
- name: brew kubernetes-cli
  shell: brew install kubernetes-cli
- name: brew libyaml
  shell: brew install libyaml
- name: brew python
  shell: brew install python
- name: brew rename
  shell: brew install rename
- name: brew tig
  shell: brew install tig
- name: brew tmux
  shell: brew install tmux
- name: brew tree
  shell: brew install tree
- name: brew watch
  shell: brew install watch
- name: brew wget
  shell: brew install wget
- name: brew xpdf
  shell: brew install xpdf
- name: brew xz
  shell: brew install xz
- name: brew zopfli
  shell: brew install zopfli
- name: brew ansible
  shell: brew install ansible
- name: brew docker-compose
  shell: brew install docker-compose
- name: brew starship
  shell: brew install starship
- name: brew powerline-go
  shell: brew install powerline-go
- name: brew mas
  shell: brew install mas
- name: brew openvpn
  shell: brew install openvpn
- name: brew Schniz/tap/fnm # curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash
  shell: brew install Schniz/tap/fnm # curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash
