---
- name: brew tap homebrew/core
  shell: brew tap homebrew/core
- name: brew tap homebrew/cask-versions
  shell: brew tap homebrew/cask-versions
- name: brew tap homebrew/cask-fonts
  shell: brew tap homebrew/cask-fonts
- name: brew tap AdoptOpenJDK/openjdk
  shell: brew tap AdoptOpenJDK/openjdk
