#!/bin/bash

export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.config/composer/vendor/bin
export PATH=$PATH:$HOME/.fnm
export PATH=$PATH:$HOME/.sman/bin
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
export PATH=$PATH:$HOME/.cargo/bin

export I3BLOCKS=$HOME/i3blocks-contrib

export SHELL=/usr/bin/zsh
export EDITOR='nano'
export GNUPGHOME=$DOTFILES/.gnupg
export GPG_TTY=$(tty)

export NAVI_PATH="$HOME/.navi"

export PATH=$PATH:~/.go/bin
export GOPATH=~/go
