#!/bin/zsh

npm i -g @angular/cli
npm i -g gatsby-cli
npm i -g bower
npm i -g create-react-app
npm i -g create-react-native-app
npm i -g eslint
npm i -g eslint-config-airbnb
npm i -g eslint-config-prettier
npm i -g eslint-plugin-flowtype
npm i -g eslint-plugin-import
npm i -g eslint-plugin-jsx-a11y
npm i -g eslint-plugin-prettier
npm i -g eslint-plugin-react
npm i -g gulp
npm i -g http-server
npm i -g nodemon
npm i -g webpack

