#!/bin/zsh

sudo rm -rf /etc/systemd/urxvtd@service
echo "[Unit]
Description=RXVT-Unicode Daemon

[Service]
User=%i
ExecStart=/usr/bin/urxvtd -q -o

[Install]
WantedBy=multi-user.target" | sudo tee -a /etc/systemd/system/urxvtd@.service
sudo systemctl enable urxvtd@$USER.service
sudo systemctl start urxvtd@$USER.service
