#!/bin/bash

ask_for_confirmation "install extensions?"
if answer_is_yes; then
  for vscode_extensions in $(cat $DOTFILES/packages/vscode); do
    echo "vscode_extensions, $vscode_extensions"
    codium --install-extension $vscode_extensions
  done
fi

