#!/bin/bash

yay_arch() {
    pinfo "@yay @arch #software @start" 

    git clone https://aur.archlinux.org/yay.git /tmp/yay
    chown -R $USER /tmp/yay
    cd /tmp/yay
    makepkg -si --noconfirm
    cd $HOME

    psuccess "@yay @arch #software @done"
}
