---
- name: Playbook for archlinux
  hosts: localhost
  connection: local
  tasks:
    - name: Enable tty_tickets
      lineinfile: 'dest=/etc/sudoers state=present line="Defaults tty_tickets" validate="visudo -cf %s"'
      become: yes
      when: ansible_os_family == "Darwin"
