---
- name: enabling service sshd
  systemd: name=sshd state=started enabled=true

- name: enabling service acpid
  systemd: name=acpid state=started enabled=true

- name: enabling service ntpd
  systemd: name=ntpd state=started enabled=true

- name: enabling service cronie
  systemd: name=cronie state=started enabled=true

- name: enabling service avahi-daemon
  systemd: name=avahi-daemon state=started enabled=true

- name: enabling service fstrim.timer
  systemd: name=fstrim.timer state=started enabled=true

- name: enabling service dhcpcd.service
  systemd: name=dhcpcd.service state=started enabled=true

- name: enabling service tlp.service
  systemd: name=tlp.service state=started enabled=true

# CONFIGURATION

- name: copying .xinitrc
  copy:
    src: .xinitrc
    dest: /home/{{user_name}}
    owner: "{{ user_name }}"
    force: yes

# enabling ssh
# nano /etc/ssh/sshd_config
# systemctl start sshd
# echo "[SSH service status ]"
# systemctl enable sshd
# echo "
# PermitRootLogin no
# Port 9812
# X11Forwarding no
# " | tee --append /etc/ssh/sshd_config

# AWS CLI

# CHROME

# CURL WGET

# DOCKER

# GIT

# GRADLE

# LARAVEL

# LXD

# MARIADB

# MONGODB

# NPM

# NVM

# POSTRESQL

# SPOTIFY

# SQLSERVER

# TERMINAL

# VAGRANT

# VIRTUALBOX

# VSCODE

# WEECHATS

# GNOME

# - name: 'Configuring Gnome'
#   gsetting: user={user_name}
#             key=org.gnome.desktop.privacy
#             value=false

#   gsettings set org.gnome.desktop.privacy remember-recent-files false
#   gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
#   gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
#   gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
#   gsettings set org.gnome.desktop.interface clock-show-date true
#   gsettings set org.gnome.desktop.interface clock-show-seconds true
#   gsettings set org.gnome.desktop.calendar show-weekdate true
#   gsettings set org.gnome.desktop.background show-desktop-icons true
#   gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
#   gsettings set org.gnome.shell.extensions.user-theme name 'Arc-Dark'
#   gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'
#   gsettings set org.gnome.desktop.interface icon-theme 'Arc'
#   gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'full'
#   gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
#   gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
#   gsettings set org.gnome.mutter dynamic-workspaces false
#   gsettings set org.gnome.shell.overrides dynamic-workspaces false
#   gsettings set org.gnome.desktop.wm.preferences num-workspaces 6
#   gsettings set org.gnome.shell.overrides workspaces-only-on-primary false
#   gsettings set org.gnome.desktop.wm.preferences workspace-names "['Code1','Code2','Code3','Code4', 'Code5', 'Code6']"
#   gsettings set org.gnome.desktop.search-providers disabled "['org.gnome.Contacts.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.GPaste.Ui.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Epiphany.desktop']"
#   gsettings set org.gnome.shell enabled-extensions "['workspace-grid@mathematical.coffee.gmail.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'battery-percentage@mubaris.github.io', 'disable-workspace-switcher-popup@github.com', 'docker_status@gpouilloux', 'harddiskled@bijidroid.gmail.com', 'openweather-extension@jenslody.de', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'sound-output-device-chooser@kgshank.net', 'taskwhisperer-extension@infinicode.de', 'touchpad-indicator@orangeshirt', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'simplenetspeed@biji.extension', 'favorites@cvine.org']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Shift><Alt>exclam']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Shift><Alt>at']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Shift><Alt>numbersign']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Shift><Alt>dollar']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Shift><Alt>percent']"
#   gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Shift><Alt>asciicircum']"
#   gsettings set org.gnome.desktop.interface enable-animations false
#   gsettings set org.gnome.nautilus.desktop network-icon-visible false
#   gsettings set org.gnome.nautilus.desktop background-fade false
#   gsettings set org.gnome.desktop.default-applications.terminal exec urxvtc
#   gsettings set org.gnome.desktop.default-applications.terminal exec-arg "'-e'"
#   gsettings set org.gnome.desktop.screensaver picture-uri ''
#   gsettings set org.gnome.desktop.background primary-color '#000000'
#   gsettings set org.gnome.desktop.background secondary-color '#000000'
#   gsettings set org.gnome.desktop.background picture-uri ''
#   gsettings set org.gnome.desktop.screensaver primary-color '#000000'
#   gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 11'
#   #gsettings set org.gnome.setings-daemon.plugins.color night-light-enabled true
#   #gsettings set org.gnome.setings-daemon.plugins.color night-light-temperature 4500

- name: Execute the POSTINSTALL SCRIPT
  command: sh postinstall.sh
