style:
  tag:
    color: grey
    width_percentage: 26
    min_width: 20
  comment:
    color: blue
    width_percentage: 42
    min_width: 45
  snippet:
    color: dark_green
finder:
  command: fzf
shell:
  command: zsh

cheats:
  paths:
    - $HOME/.navi
    - $HOME/.user/.work/.navi
