#!/bin/bash

# source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# eval "$(ssh-agent -s)"
# if [ -n "${SSH_AGENT_PID}" ]; then
#   eval "$(ssh-agent -k)"
# fi

eval "$(starship init zsh)"
eval "$(fnm env)"

# if [ -x "$(command -v gdircolors)" ]; then
#   eval $(gdircolors -b ~/bliss.dircolors)
# fi

# https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget
eval "$(navi widget zsh)"
