#!/bin/zsh

# keychain --nogui --quiet $HOME/.ssh/id_rsa

# eval "$(starship init zsh)"
eval "$(fnm env)"

if [ -x "$(command -v dircolors)" ]; then eval "$(dircolors -b $HOME/.dircolors)"; fi

export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/sqlite/lib/pkgconfig"
export PATH="$PATH":"$HOME/.pub-cache/bin"
