#!/bin/zsh

# keychain --nogui --quiet $HOME/.ssh/id_rsa

eval $(gdircolors ~/bliss.dircolors)

# SQLite
# export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"
# export PKG_CONFIG_PATH="/opt/homebrew/opt/sqlite/lib/pkgconfig"
