export SILENT_INSTALL=true
export PATH_FOR_SCRIPTS="$(pwd)/00-INSTALLER/02-SCRIPTS"

if [ -z "$VSCODE_CONTAINER" ]
then
    echo ">>> NOT IS A VSCODE CONTANER ENVIRONMENT"
else
    echo ">>> VSCODE ENVIRONMENT DETECTED"
    cd $PATH_FOR_SCRIPTS
fi

source "./01-INSTALLER--ALPINE.sh"

print_success ">>> BOOTSTRAPING FINALIZED..."
