
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

choco install jre8 -y
choco install chocolateygui -y
choco install firefox -y
choco install 7zip.install -y
choco install winrar -y
choco install notepadplusplus.install  -y
choco install vlc  -y
choco install git.install  -y
choco install javaruntime -y
choco install putty.install  -y
choco install nodejs.install  -y
choco install skype -y
choco install filezilla  -y
choco install curl  -y
choco install wget -y
choco install python2  -y
choco install paint.net  -y
choco install php  -y
choco install ruby  -y
choco install vscode  -y
choco install cdburnerxp  -y
choco install python3  -y
choco install gimp  -y
choco install winscp  -y
choco install chromium  -y
choco install treesizefree  -y
choco install dropbox  -y
choco install firefoxesr  -y
choco install sql-server-management-studio  -y
choco install intellijidea-ultimate  -y
choco install rubymine  -y
choco install golang  -y
choco install googledrive  -y
choco install vagrant  -y
choco install puppet  -y
choco install steam  -y
choco install cmake  -y
choco install mysql.workbench  -y
choco install cmder  -y
choco install spotify  -y
choco install maven  -y
choco install docker  -y
choco install gradle  -y
choco install slack  -y
choco install pandoc  -y
choco install webexplayer -y
choco install evernote -y
choco install redis-64  -y
choco install kubernetes-cli  -y
choco install cpu-z.install  -y
choco install postman  -y
choco install mongodb  -y
choco install telegram.install  -y
choco install tomcat  -y
choco install docker-compose  -y
choco install googlechrome -y
choco install office365proplus  -y
choco install plantuml  -y
choco install studio3t  -y
choco install whatsapp  -y
choco install mirc  -y
choco install logitech-options -y
choco install cacher -y
choco install pycharm -y
choco install goland -y
choco install plexmediaserver -y
choco install cue -y
